# Generated by Django 3.1.1 on 2020-09-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_priority',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
