# Generated by Django 3.1.1 on 2020-09-11 19:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0004_auto_20200911_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='todo',
            unique_together={('user', 'details')},
        ),
    ]
