# Generated by Django 3.1.1 on 2020-09-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20200911_1930'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='todo',
            unique_together=set(),
        ),
    ]
